### ISSUE TITLE
EUNSUPPORTEDPROTOCOL during npm install

### ISSUE THREAD

**Issue by dodgex** [johnny-quesada-developer/react-native-global-state-hooks#3]
After a long time i got back to my old react native app and tried to update it. When installing latest version of this package i get an `npm ERR! Unsupported URL Type "workspace:": workspace:*` error. I was able to bypass it with `npm i react-native-global-state-hooks --legacy-peer-deps` to get the package installed, but now everytime i try to install something new the error repeats unless i remove this package.

From checking this repository it seems the issue is in your [package.json `peerDependencies`](https://github.com/johnny-quesada-developer/react-native-global-state-hooks/blob/master/package.json#L65).

Any chance to get a fix for this issue? :)

```
% npm i react-native-global-state-hooks                   
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dodge/.npm/_logs/2023-03-11T08_46_13_491Z-debug-0.log
```

```
% cat /Users/dodge/.npm/_logs/2023-03-11T08_46_13_491Z-debug-0.log

0 verbose cli /usr/local/Cellar/node/19.7.0/bin/node /usr/local/bin/npm
1 info using npm@9.5.0
2 info using node@v19.7.0
3 timing npm:load:whichnode Completed in 2ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 3ms
6 timing config:load:builtin Completed in 4ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/Users/dodge/Documents/projects/app-upd/mypp/.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:/Users/dodge/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 0ms
16 timing config:load Completed in 8ms
17 timing npm:load:configload Completed in 8ms
18 timing npm:load:mkdirpcache Completed in 0ms
19 timing npm:load:mkdirplogs Completed in 1ms
20 verbose title npm i react-native-global-state-hooks
21 verbose argv "i" "react-native-global-state-hooks"
22 timing npm:load:setTitle Completed in 2ms
23 timing config:load:flatten Completed in 2ms
24 timing npm:load:display Completed in 3ms
25 verbose logfile logs-max:10 dir:/Users/dodge/.npm/_logs/2023-03-11T08_46_13_491Z-
26 verbose logfile /Users/dodge/.npm/_logs/2023-03-11T08_46_13_491Z-debug-0.log
27 timing npm:load:logFile Completed in 3ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 20ms
31 timing arborist:ctor Completed in 1ms
32 silly logfile start cleaning logs, removing 1 files
33 silly logfile done cleaning log files
34 timing idealTree:init Completed in 654ms
35 timing idealTree:userRequests Completed in 3ms
36 silly idealTree buildDeps
37 silly fetch manifest react-native-global-state-hooks@*
38 timing arborist:ctor Completed in 0ms
39 http fetch GET 200 https://registry.npmjs.org/react-native-global-state-hooks 1384ms (cache revalidated)
40 silly fetch manifest react@18.2.0
41 http fetch GET 200 https://registry.npmjs.org/react 9ms (cache hit)
42 timing idealTree Completed in 2068ms
43 timing command:i Completed in 2076ms
44 verbose stack Error: Unsupported URL Type "workspace:": workspace:*
44 verbose stack     at unsupportedURLType (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:327:15)
44 verbose stack     at fromURL (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:387:13)
44 verbose stack     at Function.resolve (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:83:12)
44 verbose stack     at [nodeFromEdge] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1068:37)
44 verbose stack     at async [loadPeerSet] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1326:23)
44 verbose stack     at async [buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:929:11)
44 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:207:7)
44 verbose stack     at async Promise.all (index 1)
44 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:159:5)
44 verbose stack     at async Install.exec (/usr/local/lib/node_modules/npm/lib/commands/install.js:146:5)
45 verbose cwd /Users/dodge/Documents/projects/app-upd/myapp
46 verbose Darwin 22.3.0
47 verbose node v19.7.0
48 verbose npm  v9.5.0
49 error code EUNSUPPORTEDPROTOCOL
50 error Unsupported URL Type "workspace:": workspace:*
51 verbose exit 1
52 timing npm Completed in 2117ms
53 verbose unfinished npm timer reify 1678524373531
54 verbose unfinished npm timer reify:loadTrees 1678524373534
55 verbose unfinished npm timer idealTree:buildDeps 1678524374193
56 verbose unfinished npm timer idealTree:#root 1678524374194
57 verbose code 1
58 error A complete log of this run can be found in:
58 error     /Users/dodge/.npm/_logs/2023-03-11T08_46_13_491Z-debug-0.log
```

**Comment by johnny-quesada-developer** [comment]
Hi @dodgex , thank you so much for reporting, Im working on the fix right now and it will be release today in a while.

Sorry for the inconveniences.

**Comment by johnny-quesada-developer** [comment]
Hi, @dodgex the **peerDependencies** of the packages where updated to avoid the **npm** install problems. Thanks for using the package, and sorry again for the inconvenience.

Don't hesitate about reporting whatever other odd behaviour or doubt. Have a good day.

**Comment by dodgex** [comment]
Thank you for this fast update!

Now it has a problem with the fact that you have react with version `^17.0.0` in peer dependencies, but i have react `18.2.0` due to react native `0.71.4` in my project.

But i found that i can bypass that by overriding it...

```
  "overrides": {
    "react-native-global-state-hooks": {
      "react": "$react"
    }
  },
```

I do not know if it is possible to specify the version in a way where 17 & 18 are supported? :D

**Comment by johnny-quesada-developer** [comment]
> Thank you for this fast update!
> 
> Now it has a problem with the fact that you have react with version `^17.0.0` in peer dependencies, but i have react `18.2.0` due to react native `0.71.4` in my project.
> 
> But i found that i can bypass that by overriding it...
> 
> ```
>   "overrides": {
>     "react-native-global-state-hooks": {
>       "react": "$react"
>     }
>   },
> ```
> 
> I do not know if it is possible to specify the version in a way where 17 & 18 are supported? :D

Hi @dodgex , 

Thank you so much again... the peerDependency was fixed:
```
"react": ">=17.0.0"
```

Now it will allow to use any version equal or higher than the **17** without any workaround, thank you so much for report.
